### ISSUE TITLE
Will this package support Laravel 9?

### ISSUE THREAD

**Issue by LukeTowers** [luisdalmolin/laravel-mandrill-driver#25] opened 2021-12-09 03:08 UTC
Laravel 9 moved to Symfony Mailer, see https://github.com/laravel/framework/pull/38481

**Comment by therobfonz** [comment] 2021-12-09 11:19
I don't really use Mandrill anymore, but I do plan on supporting Laravel 9, although it might not be right away. I will of course accept any PRs from people who use the package daily and can test easier than I can since I no longer have Mandrill access.

**Comment by nickurt** [comment] 2022-01-07 15:31
@LukeTowers You can use [symfony/mailchimp-mailer](https://github.com/symfony/mailchimp-mailer)

**Comment by ajsheldon93** [comment] 2022-02-08 19:30
Confirmed that this package doesn't work in L9, but you can just use the builtin SMTP instead. Credentials are under "settings" in your mandrillapp.com dashboard. Seems to work fine.

**Comment by therobfonz** [comment] 2022-02-08 20:29
Thanks everyone! In the process of transferring this package to someone who uses Mandrill still. It will have a new maintainer in the coming days who will do the Laravel 9 upgrade.

**Comment by JayBizzle** [comment] 2022-02-28 13:59
> Thanks everyone! In the process of transferring this package to someone who uses Mandrill still. It will have a new maintainer in the coming days who will do the Laravel 9 upgrade.

Any updates on the new maintainer?

**Comment by brandonferens** [comment] 2022-04-14 13:46
Yes, we just merged a PR for the upgrade to Laravel 9. Please update your composer.json to require `^4.0.0`.

**Closed by brandonferens** 2022-04-14 13:46 UTC
